const TYPES = {
    GET_API_DTBOT: "GET_API_DTBOT",
    GET_API_DTCONFIG: "GET_API_DTCONFIG",
    GET_API_STBOT: "GET_API_STBOT",
    GET_API_STCONFIG: "GET_API_STCONFIG",
    //
    POST_API_DTBOT: "POST_API_DTBOT",
    POST_API_DTCONFIG: "POST_API_DTCONFIG",
    POST_API_STBOT: "POST_API_STBOT",
    POST_API_STCONFIG: "POST_API_STCONFIG",
    //
    PUT_API_DTBOT: "POST_API_DTBOT",
    PUT_API_DTCONFIG: "POST_API_DTCONFIG",
    PUT_API_STBOT: "POST_API_STBOT",
    PUT_API_STCONFIG: "POST_API_STCONFIG",
    //
    DELETE_API_DTBOT: "POST_API_DTBOT",
    DELETE_API_DTCONFIG: "POST_API_DTCONFIG",
    DELETE_API_STBOT: "POST_API_STBOT",
    DELETE_API_STCONFIG: "POST_API_STCONFIG",
}

export default TYPES